/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lua_java_Main */

#ifndef _Included_lua_java_Main
#define _Included_lua_java_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lua_java_Main
 * Method:    doFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lua_1java_Main_doFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
